# This is a basic workflow to help you get started with Actions

name: Angular CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Node.js (Angular requires Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # Install dependencies
      - name: Install Angular CLI and dependencies
        run: |
          npm ci
          npm install -g @angular/cli

      # Build the Angular project
      - name: Build Angular project
        run: ng build

      # Optionally: Run tests (uncomment if you have tests to run)
      # - name: Run Angular tests
      #   run: ng test --watch=false
